=== dzheleznyakov/ZhLingvoBackend/src/main/resources/xml/dictionary.dtd
<!ELEMENT dictionary (word*)>
<!ATTLIST dictionary lang NMTOKEN #REQUIRED>

<!ELEMENT word (name, transcription*, semanticBlock*, formException*)>
<!ATTLIST word id ID #REQUIRED>

<!ELEMENT name EMPTY>
<!ATTLIST name value CDATA #REQUIRED
               form NMTOKENS #IMPLIED>

<!ELEMENT transcription EMPTY>
<!ATTLIST transcription remark CDATA #IMPLIED
                        ipa CDATA #REQUIRED>

<!ELEMENT semanticBlock (posBlock*)>

<!ELEMENT posBlock (meaning*)>
<!ATTLIST posBlock pos NMTOKEN #REQUIRED>

<!ELEMENT meaning (translation*, example*)>
<!ATTLIST meaning remark CDATA #IMPLIED>

<!ELEMENT translation EMPTY>
<!ATTLIST translation value CDATA #REQUIRED
                      elaboration CDATA #IMPLIED>

<!ELEMENT example EMPTY>
<!ATTLIST example remark CDATA #IMPLIED
                  expression CDATA #IMPLIED
                  explanation CDATA #IMPLIED>

<!ELEMENT formException (name+)>
<!ATTLIST formException pos NMTOKEN #REQUIRED>

=== dzheleznyakov/ZhLingvoBackend/src/test/resources/xml/test_dictionary.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE dictionary SYSTEM "dictionary.dtd">

<dictionary lang="En">
  <word id="uuid7a631e0d-5d91-40c8-a0b2-b8cef2eb97e3">
    <name value="man" />
    <transcription ipa="man" />
    <semanticBlock>
      <posBlock pos="NOUN">
        <meaning>
          <translation value="человек" />
        </meaning>
        <meaning>
          <translation value="мужчина" />
        </meaning>
      </posBlock>
    </semanticBlock>
    <formException pos="NOUN">
      <name value="men" form="Number.PLURAL NounCase.NOMINATIVE" />
    </formException>
  </word>
  <word id="uuid89b7820d-3e3d-4ea6-a7d5-190e485c5164">
    <name value="box" />
    <transcription ipa="bɒks" />
    <semanticBlock>
      <posBlock pos="NOUN">
        <meaning>
          <translation value="коробка" />
          <translation value="ящик" />
          <translation value="сундук" />
          <translation value="сумка, вместилище" />
        </meaning>
        <meaning>
          <translation value="ящичек" elaboration="стола" />
          <translation value="коробочка" elaboration="для всяких мелочей" />
          <translation value="шкатулка" />
          <example expression="witness box" explanation="место в суде, где сидят свидетели" />
          <example expression="music box" explanation="музыкальная шкатулка" remark="амер." />
          <example expression="musical box" explanation="музыкальная шкатулка" remark="брит." />
          <example expression="shooting box" explanation="охотничья сумка" />
        </meaning>
        <meaning remark="рел.">
          <translation value="дарохранительница" />
          <translation value="дароносица" />
        </meaning>
      </posBlock>
    </semanticBlock>
    <semanticBlock>
      <posBlock pos="NOUN">
        <meaning>
          <translation value="удар" />
        </meaning>
      </posBlock>
      <posBlock pos="VERB">
        <meaning>
          <translation value="боксировать" />
        </meaning>
      </posBlock>
    </semanticBlock>
  </word>
</dictionary>
